// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcLMtWCNEYsUnHF2b1pYoTY4PhoiqTlc',
    appId: '1:854922712834:web:4df7c831386ba81ff5d41b',
    messagingSenderId: '854922712834',
    projectId: 'bronz-app',
    authDomain: 'bronz-app.firebaseapp.com',
    storageBucket: 'bronz-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDghDmPTvzMkB02_vvQN4QgL1bfsWUZ7E',
    appId: '1:854922712834:ios:0fff5a3d92a6b032f5d41b',
    messagingSenderId: '854922712834',
    projectId: 'bronz-app',
    storageBucket: 'bronz-app.firebasestorage.app',
    androidClientId: '854922712834-u5445ougcal67qnap1v6f2dnftf5u1o9.apps.googleusercontent.com',
    iosClientId: '854922712834-1dvu4pquami7sadjchqpj7q7ev4jrmvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plageReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJcLMtWCNEYsUnHF2b1pYoTY4PhoiqTlc',
    appId: '1:854922712834:web:171371c624a4a5c4f5d41b',
    messagingSenderId: '854922712834',
    projectId: 'bronz-app',
    authDomain: 'bronz-app.firebaseapp.com',
    storageBucket: 'bronz-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDghDmPTvzMkB02_vvQN4QgL1bfsWUZ7E',
    appId: '1:854922712834:ios:0fff5a3d92a6b032f5d41b',
    messagingSenderId: '854922712834',
    projectId: 'bronz-app',
    storageBucket: 'bronz-app.firebasestorage.app',
    androidClientId: '854922712834-u5445ougcal67qnap1v6f2dnftf5u1o9.apps.googleusercontent.com',
    iosClientId: '854922712834-1dvu4pquami7sadjchqpj7q7ev4jrmvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plageReview',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLt2iZ2OmYt0EpTfNfFyhSinN5_qTMak0',
    appId: '1:854922712834:android:886817134db16844f5d41b',
    messagingSenderId: '854922712834',
    projectId: 'bronz-app',
    storageBucket: 'bronz-app.firebasestorage.app',
  );
}
